# Generated by Django 5.1.2 on 2024-10-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_person_addres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='file',
        ),
    ]
